name: Rails Multisite Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ok_to_fail == ' - Ok to fail' }}
    name: "Ruby ${{ matrix.ruby }} - Rails ${{ matrix.rails }}${{ matrix.ok_to_fail }}"
    env:
      RAILS_MULTISITE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]
        rails: ["5", "6.0", "6.1"]
        ok_to_fail: [""]
        exclude:
          - ruby: 3.0
            rails: 5
        include:
          - ruby: "2.7"
            rails: master
            ok_to_fail: " - Ok to fail"
          - ruby: "3.0"
            rails: master
            ok_to_fail: " - Ok to fail"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup gems
        run: |
          bundle config set path vendor/bundle
          BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle install --jobs=3 --retry=3 --without development
      - name: Rubocop
        run: BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle exec rubocop
      - name: Tests
        run: BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle exec rspec
