name: Rails Multisite Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == 'OK to fail' }}
    name: "Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }} / ${{ matrix.experimental }}"
    env:
      RAILS_MULTISITE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.4", "2.5", "2.6", "2.7"]
        gemfile: ["rails_5", "rails_6"]
        experimental: [""]
        exclude:
          - ruby: 2.4
            gemfile: rails_6
        include:
          - ruby: "2.5"
            gemfile: rails_master
            experimental: "OK to fail"
          - ruby: "2.6"
            gemfile: rails_master
            experimental: "OK to fail"
          - ruby: "2.7"
            gemfile: rails_master
            experimental: "OK to fail"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.gemfile }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.gemfile }}-gems-
      - name: Setup gems
        run: |
          bundle config set path vendor/bundle
          BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle install --jobs=3 --retry=3 --without development
      - name: Rubocop
        run: BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle exec rubocop
      - name: Tests
        run: BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle exec rspec
