name: Rails Multisite Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ok_to_fail == ' - Ok to fail' }}
    name: "Ruby ${{ matrix.ruby }} - Rails ${{ matrix.rails }}${{ matrix.ok_to_fail }}"
    env:
      RAILS_MULTISITE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.4", "2.5", "2.6", "2.7"]
        rails: ["5", "6"]
        ok_to_fail: [""]
        exclude:
          - ruby: 2.4
            rails: 6
        include:
          - ruby: "2.5"
            rails: master
            ok_to_fail: " - Ok to fail"
          - ruby: "2.6"
            rails: master
            ok_to_fail: " - Ok to fail"
          - ruby: "2.7"
            rails: master
            ok_to_fail: " - Ok to fail"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.rails }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.rails }}-gems-
      - name: Setup gems
        run: |
          bundle config set path vendor/bundle
          BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle install --jobs=3 --retry=3 --without development
      - name: Rubocop
        run: BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle exec rubocop
      - name: Tests
        run: BUNDLE_GEMFILE=$PWD/$RAILS_MULTISITE_GEMFILE bundle exec rspec
